# fly.toml file generated for codeday-labs-gql on 2021-11-17T13:59:31-05:00

app = "codeday-labs-gql"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
