# fly.toml file generated for codeday-labs-gql on 2023-05-24T10:06:00-07:00

app = "codeday-labs-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[experimental]
  auto_rollback = true

[env]
  DEBUG = "codeday:labs:*"
  DEBUG_HIDE_DATE = "1"
  DEBUG_COLORS = "1"