# fly.toml file generated for codeday-labs-gql on 2023-05-24T10:06:00-07:00

app = "codeday-labs-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[[services]]
  protocol = "tcp"
  internal_port = 5001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[experimental]
  auto_rollback = true

[env]
  DEBUG = "codeday:labs:*"
  DEBUG_HIDE_DATE = "1"
  DEBUG_COLORS = "1"